"""empty message

Revision ID: 903d2f48d84f
Revises: 
Create Date: 2023-09-12 10:06:04.615984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903d2f48d84f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('learned_word')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('password', sa.VARCHAR(length=150), nullable=True),
    sa.Column('Username', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('learned_word',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('User_words', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['User_words'], ['user.library'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('User_words')
    )
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
