"""empty message

Revision ID: ca9ed087bbb2
Revises: eb1022e91398
Create Date: 2023-09-12 22:34:56.997202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9ed087bbb2'
down_revision = 'eb1022e91398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learned_word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learned_word', schema=None) as batch_op:
        batch_op.drop_column('definition')

    # ### end Alembic commands ###
